Repository Mythacri/Mythacri-Foundry-Scripts, pull requests merged in 2023-11, with the labels that each got.

#84 [#75, #82] Add handling for wildcard resources in recipes, fix up crafting handler ui
  languages/en.json
  scripts/modules/applications/crafting-application.mjs
  scripts/modules/data/crafting.mjs
  scripts/modules/data/models/recipe-item.mjs
  styles/mythacri.css
  templates/crafting-handler.hbs
Labels: enhancement

#86 [#85] Fix error on vehicle equipment and siege weapons
  scripts/modules/data/crafting.mjs
Labels: bug

#88 [#87] Witch concentration
  scripts/modules/data/concentration.mjs
  scripts/setup.mjs
Labels: enhancement

#91 Upkeep fixes
  module.json
  scripts/modules/data/crafting.mjs
  scripts/modules/data/mayhem.mjs
  styles/mythacri.css
  templates/parts/long-rest.hbs
  templates/recipe-sheet.hbs
Labels: bug

#96 [#95] Remove all currencies, introduce 'marbles'
  languages/en.json
  scripts/modules/system-config.mjs
Labels: enhancement

#97 Amend some linting issues and missing comments
  scripts/modules/applications/crafting-application.mjs
  scripts/modules/applications/recipe-sheet.mjs
  scripts/modules/applications/runes-config.mjs
  scripts/modules/applications/soundboard.mjs
  scripts/modules/data/concentration.mjs
  scripts/modules/data/settings.mjs
  scripts/modules/interface.mjs
Labels: bug, documentation

#105 [#94, #99, #100, #101] Spirit binding
  languages/en.json
  scripts/modules/applications/crafting-application.mjs
  scripts/modules/data/crafting.mjs
  scripts/modules/system-config.mjs
  styles/mythacri.css
  templates/parts/resource-types.hbs
Labels: enhancement

#106 Various recipe sheet improvements
  languages/en.json
  scripts/modules/applications/recipe-sheet.mjs
  scripts/modules/data/models/recipe-item.mjs
  scripts/modules/data/pips.mjs
  scripts/modules/data/settings.mjs
  styles/mythacri.css
  templates/recipe-sheet.hbs
  templates/runes-target.hbs
Labels: enhancement

#107 [#18] New Weapon Proficiencies
  scripts/modules/system-config.mjs
Labels: enhancement

#109 [#108] Create github action and update manifest
  .github/workflows/main.yml
  module.json
Labels: enhancement

#115 [#110, #112, #114] Iron Chin, Moxie Feature, resources css
  languages/en.json
  scripts/modules/system-config.mjs
  styles/mythacri.css
Labels: enhancement
