Repository Mythacri/Mythacri-Foundry-Scripts, pull requests merged in 2024-02, with the labels that each got.

#147 [#126, #146, #148, #149] Upkeep and fixes for compatibility with dnd5e version 3.0.x
  .github/workflows/main.yml
  .gitignore
  README.md
  assets/LICENSE
  assets/icons/crafting-node.webp
  assets/icons/marble.webp
  assets/icons/skull-and-bones.svg
  assets/statuses/dazed.svg
  assets/statuses/exhaustion-1.svg
  assets/statuses/exhaustion-10.svg
  assets/statuses/exhaustion-2.svg
  assets/statuses/exhaustion-3.svg
  assets/statuses/exhaustion-4.svg
  assets/statuses/exhaustion-5.svg
  assets/statuses/exhaustion-6.svg
  assets/statuses/exhaustion-7.svg
  assets/statuses/exhaustion-8.svg
  assets/statuses/exhaustion-9.svg
  assets/statuses/exhaustion.svg
  assets/statuses/impaired.svg
  languages/en.json
  module.json
  scripts/modules/applications/crafting-application.mjs
  scripts/modules/applications/soundboard.mjs
  scripts/modules/applications/storage-sheet.mjs
  scripts/modules/data/award.mjs
  scripts/modules/data/combat.mjs
  scripts/modules/data/crafting.mjs
  scripts/modules/data/mayhem.mjs
  scripts/modules/data/models/recipe-item.mjs
  scripts/modules/data/pips.mjs
  scripts/modules/data/resting.mjs
  scripts/modules/data/settings.mjs
  scripts/modules/data/storage.mjs
  scripts/modules/data/token-auras.mjs
  scripts/modules/interface.mjs
  scripts/modules/system-config.mjs
  scripts/setup.mjs
  styles/mythacri.css
  templates/crafting-application.hbs
  templates/crafting-handler.hbs
  templates/parts/crafting-buttons.hbs
  templates/parts/crafting-recipe.hbs
  templates/parts/crafting-selected.hbs
  templates/parts/resource-types.hbs
  templates/parts/runes-config-icon.hbs
  templates/parts/storage-inventory.hbs
  templates/storage-sheet.hbs
Labels: enhancement, tech-debt

#153 [#150, #151, #152] Hotfix bugs
  scripts/modules/applications/storage-sheet.mjs
  scripts/modules/system-config.mjs
  styles/mythacri.css
Labels: bug

#158 [#157] Add bounce animation hook
  scripts/modules/data/combat.mjs
Labels: enhancement

#159 Skull and bones edit
  assets/LICENSE
  assets/icons/skull-and-bones.svg
Labels: bug
